# Generated by Django 4.2.7 on 2023-11-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amout',
            new_name='amount',
        ),
    ]
