# Generated by Django 4.2.7 on 2023-12-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Описание'),
        ),
    ]
